<div class="donation-message">
    <div class="donation-title">Freedom Fighter Support</div>
    After you checkout, we'll donate
    <span class="amount"><?php echo $this->getCalculatedAmountFormatted(); ?></span>
    to the organization of your choice - all at no charge to you.
    <br>Why? Because with every purchase, we donate to an organization that shares our values. <a class="lmdonations" href="<?php echo $this->getUrl('donations') ?>" target="_blank">Learn more</a>
</div>