<div class="donation-message">
    <span class="required">*</span> Once your order is submitted below, this purchase will
    automatically result in Ammo.net donating <span
        class="amount"><?php echo $this->getCalculatedAmountFormatted(); ?></span> -
    that's <?php echo $this->getCommissionRateFormatted(); ?> of your current order's subtotal,
    excluding shipping costs - to the pro-2nd Amendment or pro-military organization of your choice.
    <strong>This is not a separate cost and you are not charged for this.</strong> Instead, we make
    this <?php echo $this->getCommissionRateFormatted(); ?> donation on behalf of every order
    because we believe in supporting those who protect our freedoms.
</div>
